"""Vertiv parser.

Vertiv only has a Q1 folder in this dataset (Q2 is absent entirely, not just
one document type), so this parser is only ever exercised for Q1. The press
release is prose for headline KPIs plus a clean 'Regional Segment Results'
table (label, then five columns: this-year, prior-year, delta, delta%,
organic delta% - we only need the first, 'this-year', column).
"""
import re
from .common import to_number, find_sentence, find_last_in_run, find_two

CURRENCY = "USD"
_REGIONS = ["AMER", "APAC", "EMEA"]

# Row labels used in the results-presentation appendix's trailing-quarters
# trend tables ("Non-GAAP financial measures: Qx 2025 - Qx 2026 results")
# map to our canonical region names.
_PRES_REGION_LABELS = {"AMER": "Americas", "APAC": "Asia Pacific", "EMEA": "Europe, Middle East & Africa"}


def parse_press_release(text: str) -> dict:
    kpis = {"currency": CURRENCY}

    m = re.search(r"Net sales of \$([\d,]+) million", text, re.I)
    if m:
        kpis["revenue"] = to_number(m.group(1))

    m = re.search(r"[Oo]perating profit of \$([\d,]+) million", text, re.I)
    if m:
        kpis["operating_profit"] = to_number(m.group(1))

    m = re.search(r"[Aa]djusted operating profit of \$([\d,]+) million", text, re.I)
    if m:
        kpis["adjusted_operating_profit"] = to_number(m.group(1))

    m = re.search(r"Adjusted operating margin (?:was|of) ([\d.]+)%", text, re.I)
    if m:
        kpis["adjusted_operating_margin_pct"] = to_number(m.group(1))

    m = re.search(
        r"[Nn]et cash generated by operating activities in the first quarter was \$([\d,]+) million "
        r"and adjusted free cash flow was \$([\d,]+) million",
        text, re.I,
    )
    if m:
        kpis["operating_cash_flow"] = to_number(m.group(1))
        kpis["adjusted_free_cash_flow"] = to_number(m.group(2))

    m = re.search(r"net leverage (?:of|was approximately) ~?([\d.]+)x", text, re.I)
    if m:
        kpis["net_leverage_x"] = to_number(m.group(1))

    # Vertiv's own income-statement/cash-flow tables list the CURRENT year
    # FIRST then the prior year (e.g. "March 31, 2026 ... March 31, 2025"),
    # opposite of the (prior, current) convention find_two assumes elsewhere
    # (ASML/Google use prior-then-current) - so we take the first value here.
    diluted_eps, _ = find_two(text, "Diluted")
    if diluted_eps is not None:
        kpis["diluted_eps"] = diluted_eps
    capex, _ = find_two(text, "Capital expenditures")
    if capex is not None:
        kpis["capex"] = -abs(capex)
        if "operating_cash_flow" in kpis:
            kpis["free_cash_flow"] = round(kpis["operating_cash_flow"] + kpis["capex"], 1)

    # regional segment table: label, Net sales value (this year), then more columns we ignore
    business_units = []
    seg_section = text.split("Regional Segment Results", 1)
    seg_block = seg_section[1] if len(seg_section) > 1 else ""
    op_margin_section = seg_block.split("Adjusted operating margins", 1)
    margins_block = op_margin_section[1] if len(op_margin_section) > 1 else ""
    sales_and_profit_block = op_margin_section[0]

    for region in _REGIONS:
        # first numeric occurrence of the region in the sales table = net sales
        m = re.search(re.escape(region) + r"\s*\n\s*\$?\s*([\d,.]+)", sales_and_profit_block, re.I)
        sales = to_number(m.group(1)) if m else None
        # second occurrence (after 'Adjusted operating profit') = operating profit
        prof_section = sales_and_profit_block.split("Adjusted operating profit", 1)
        op_profit = None
        if len(prof_section) > 1:
            m2 = re.search(re.escape(region) + r"\s*\n\s*\$?\s*([\d,.]+)", prof_section[1], re.I)
            op_profit = to_number(m2.group(1)) if m2 else None
        m3 = re.search(re.escape(region) + r"\s*\n\s*([\d.]+)\s*%", margins_block, re.I)
        margin = to_number(m3.group(1)) if m3 else None

        if sales is not None:
            business_units.append({
                "name": region,
                "revenue": sales,
                "operating_income": op_profit,
                "operating_margin_pct": margin,
                "currency": CURRENCY,
            })

    guidance = {}
    m = re.search(r"Second Quarter 2026 Guidance\s*\nNet sales\s*\n?\$?([\d,]+)M\s*-\s*\$?([\d,]+)M", text, re.I)
    if m:
        guidance["next_quarter_net_sales_usd_mn"] = [to_number(m.group(1)), to_number(m.group(2))]
    m = re.search(r"Full Year 2026 Guidance\s*\nNet sales\s*\n?\$?([\d,]+)M\s*-\s*\$?([\d,]+)M", text, re.I)
    if m:
        guidance["full_year_net_sales_usd_mn"] = [to_number(m.group(1)), to_number(m.group(2))]

    commentary = []
    quote = find_sentence(text, "said Giordano Albertazzi", window=500)
    if quote:
        commentary.append(quote)
    quote2 = find_sentence(text, "said Dave Cote", window=400)
    if quote2:
        commentary.append(quote2)

    return {"kpis": kpis, "business_units": business_units, "guidance": guidance, "commentary": commentary}


def _section(text: str, start_anchor: str, end_anchor: str = None, from_last: bool = False) -> str:
    """Slice text between two anchors (end_anchor optional -> to end of text).
    from_last=True splits on the LAST occurrence of start_anchor, used when an
    anchor appears twice (once in a front chart slide, once in the cleaner
    appendix table - we want the appendix version, which comes later)."""
    parts = text.split(start_anchor)
    if len(parts) < 2:
        return ""
    chunk = parts[-1] if from_last else parts[1]
    if end_anchor:
        chunk = chunk.split(end_anchor, 1)[0]
    return chunk


def parse_presentation(text: str) -> dict:
    """Vertiv's results presentation - used standalone for Q2 in this dataset
    (no press release was provided). KPIs are pulled from the appendix's
    'Non-GAAP financial measures: Qx 2025 - Qx 2026 results' trailing-quarter
    trend tables (label, then one number per quarter column - we take the
    last, i.e. most recent, column) rather than the front summary chart
    slides, whose text extraction order doesn't follow visual reading order.
    """
    kpis = {"currency": CURRENCY}

    net_sales_block = _section(text, "Net Sales(1)", "Adjusted operating margins")
    adj_op_profit_block = _section(text, "Adjusted operating profit (loss)(2)", "Net Sales(1)")
    margin_block = _section(text, "Adjusted operating margins(4)", "©")
    gaap_op_profit_block = _section(text, "Total corporate and other", from_last=True)
    cash_flow_block = _section(text, "Reconciliation of net cash provided by (used for)",
                                from_last=True)

    kpis["revenue"] = find_last_in_run(net_sales_block, "Total")
    kpis["adjusted_operating_profit"] = find_last_in_run(adj_op_profit_block, "Adjusted operating profit (loss) Total")
    kpis["adjusted_operating_margin_pct"] = find_last_in_run(margin_block, "Vertiv")
    kpis["operating_profit"] = find_last_in_run(gaap_op_profit_block, "Operating profit (loss)")
    kpis["operating_cash_flow"] = find_last_in_run(cash_flow_block, "Net cash provided by (used for) operating activities")
    kpis["adjusted_free_cash_flow"] = find_last_in_run(cash_flow_block, "Adjusted free cash flow")
    capex = find_last_in_run(cash_flow_block, "Less: Capital expenditures")
    if capex is not None:
        kpis["capex"] = -abs(capex)
        if kpis.get("operating_cash_flow") is not None:
            kpis["free_cash_flow"] = round(kpis["operating_cash_flow"] + kpis["capex"], 1)

    m = re.search(r"[Nn]et leverage:?\s*(?:of|was approximately)?\s*~?\(?(-?[\d.]+)\)?x", text)
    if m:
        kpis["net_leverage_x"] = to_number(m.group(1))
    m = re.search(r"adjusted diluted earnings per share of \$([\d.]+)", text, re.I)
    if m:
        kpis["adjusted_diluted_eps"] = to_number(m.group(1))
    # GAAP diluted EPS lives in the "Diluted EPS(1) / GAAP / <6 values>" row of
    # the per-quarter (not trailing-trend) reconciliation table - last value.
    m = re.search(r"Diluted EPS\(1\)\s*\nGAAP\s*\n((?:[ \t]*\$?-?[\d,.]+\s*\n){3,8})", text, re.I)
    if m:
        nums = re.findall(r"-?[\d,.]+", m.group(1))
        if nums:
            kpis["diluted_eps"] = to_number(nums[-1])

    business_units = []
    for region, pres_label in _PRES_REGION_LABELS.items():
        # the Net Sales table uses the short "EMEA" label while the profit/
        # margin tables spell out "Europe, Middle East & Africa" - try both.
        sales = find_last_in_run(net_sales_block, pres_label) or find_last_in_run(net_sales_block, region)
        op_profit = find_last_in_run(adj_op_profit_block, pres_label) or find_last_in_run(adj_op_profit_block, region)
        margin = find_last_in_run(margin_block, pres_label) or find_last_in_run(margin_block, region)
        if sales is not None:
            business_units.append({
                "name": region,
                "revenue": sales,
                "operating_income": op_profit,
                "operating_margin_pct": margin,
                "currency": CURRENCY,
            })

    # Guidance: each "financial guidance" slide lists its metrics' "Range:"
    # lines in a fixed order (Net Sales, Adj. Op Profit, Adj. Op Margin,
    # Adj. Diluted EPS[, Adj. Free Cash Flow for the full-year slide]).
    guidance = {}
    q3_block = _section(text, "Third quarter 2026 financial guidance", "Full year 2026 financial guidance")
    fy_block = _section(text, "Full year 2026 financial guidance", "Non-GAAP financial measures")
    range_pattern = r"Range:\s*\$?([\d,.]+)%?M?\s*-\s*\$?([\d,.]+)%?M?"
    q3_ranges = re.findall(range_pattern, q3_block)
    fy_ranges = re.findall(range_pattern, fy_block)
    if len(q3_ranges) >= 4:
        guidance["next_quarter_net_sales_usd_mn"] = [to_number(x) for x in q3_ranges[0]]
        guidance["next_quarter_adjusted_operating_profit_usd_mn"] = [to_number(x) for x in q3_ranges[1]]
        guidance["next_quarter_adjusted_operating_margin_pct"] = [to_number(x) for x in q3_ranges[2]]
        guidance["next_quarter_adjusted_diluted_eps"] = [to_number(x) for x in q3_ranges[3]]
    if len(fy_ranges) >= 4:
        guidance["full_year_net_sales_usd_mn"] = [to_number(x) for x in fy_ranges[0]]
        guidance["full_year_adjusted_operating_profit_usd_mn"] = [to_number(x) for x in fy_ranges[1]]
        guidance["full_year_adjusted_operating_margin_pct"] = [to_number(x) for x in fy_ranges[2]]
        guidance["full_year_adjusted_diluted_eps"] = [to_number(x) for x in fy_ranges[3]]
    if len(fy_ranges) >= 5:
        guidance["full_year_adjusted_free_cash_flow_usd_mn"] = [to_number(x) for x in fy_ranges[4]]

    commentary = []
    for kw in ["Second quarter net sales up", "Raising full year 2026 net sales guidance"]:
        s = find_sentence(text, kw, window=450)
        if s:
            commentary.append(s)

    return {"kpis": kpis, "business_units": business_units, "guidance": guidance, "commentary": commentary}


def parse(doc_type: str, text: str) -> dict:
    if doc_type == "press_release":
        return parse_press_release(text)
    if doc_type == "presentation":
        return parse_presentation(text)
    return {"kpis": {}, "business_units": [], "guidance": {}, "commentary": []}
