"""Vertiv parser.

Vertiv only has a Q1 folder in this dataset (Q2 is absent entirely, not just
one document type), so this parser is only ever exercised for Q1. The press
release is prose for headline KPIs plus a clean 'Regional Segment Results'
table (label, then five columns: this-year, prior-year, delta, delta%,
organic delta% - we only need the first, 'this-year', column).
"""
import re
from .common import to_number, find_sentence

CURRENCY = "USD"
_REGIONS = ["AMER", "APAC", "EMEA"]


def parse_press_release(text: str) -> dict:
    kpis = {"currency": CURRENCY}

    m = re.search(r"Net sales of \$([\d,]+) million", text, re.I)
    if m:
        kpis["revenue"] = to_number(m.group(1))

    m = re.search(r"[Oo]perating profit of \$([\d,]+) million", text, re.I)
    if m:
        kpis["operating_profit"] = to_number(m.group(1))

    m = re.search(r"[Aa]djusted operating profit of \$([\d,]+) million", text, re.I)
    if m:
        kpis["adjusted_operating_profit"] = to_number(m.group(1))

    m = re.search(r"Adjusted operating margin (?:was|of) ([\d.]+)%", text, re.I)
    if m:
        kpis["adjusted_operating_margin_pct"] = to_number(m.group(1))

    m = re.search(
        r"[Nn]et cash generated by operating activities in the first quarter was \$([\d,]+) million "
        r"and adjusted free cash flow was \$([\d,]+) million",
        text, re.I,
    )
    if m:
        kpis["operating_cash_flow"] = to_number(m.group(1))
        kpis["adjusted_free_cash_flow"] = to_number(m.group(2))

    m = re.search(r"net leverage (?:of|was approximately) ~?([\d.]+)x", text, re.I)
    if m:
        kpis["net_leverage_x"] = to_number(m.group(1))

    # regional segment table: label, Net sales value (this year), then more columns we ignore
    business_units = []
    seg_section = text.split("Regional Segment Results", 1)
    seg_block = seg_section[1] if len(seg_section) > 1 else ""
    op_margin_section = seg_block.split("Adjusted operating margins", 1)
    margins_block = op_margin_section[1] if len(op_margin_section) > 1 else ""
    sales_and_profit_block = op_margin_section[0]

    for region in _REGIONS:
        # first numeric occurrence of the region in the sales table = net sales
        m = re.search(re.escape(region) + r"\s*\n\s*\$?\s*([\d,.]+)", sales_and_profit_block, re.I)
        sales = to_number(m.group(1)) if m else None
        # second occurrence (after 'Adjusted operating profit') = operating profit
        prof_section = sales_and_profit_block.split("Adjusted operating profit", 1)
        op_profit = None
        if len(prof_section) > 1:
            m2 = re.search(re.escape(region) + r"\s*\n\s*\$?\s*([\d,.]+)", prof_section[1], re.I)
            op_profit = to_number(m2.group(1)) if m2 else None
        m3 = re.search(re.escape(region) + r"\s*\n\s*([\d.]+)\s*%", margins_block, re.I)
        margin = to_number(m3.group(1)) if m3 else None

        if sales is not None:
            business_units.append({
                "name": region,
                "revenue": sales,
                "operating_income": op_profit,
                "operating_margin_pct": margin,
                "currency": CURRENCY,
            })

    guidance = {}
    m = re.search(r"Second Quarter 2026 Guidance\s*\nNet sales\s*\n?\$?([\d,]+)M\s*-\s*\$?([\d,]+)M", text, re.I)
    if m:
        guidance["next_quarter_net_sales_usd_mn"] = [to_number(m.group(1)), to_number(m.group(2))]
    m = re.search(r"Full Year 2026 Guidance\s*\nNet sales\s*\n?\$?([\d,]+)M\s*-\s*\$?([\d,]+)M", text, re.I)
    if m:
        guidance["full_year_net_sales_usd_mn"] = [to_number(m.group(1)), to_number(m.group(2))]

    commentary = []
    quote = find_sentence(text, "said Giordano Albertazzi", window=500)
    if quote:
        commentary.append(quote)
    quote2 = find_sentence(text, "said Dave Cote", window=400)
    if quote2:
        commentary.append(quote2)

    return {"kpis": kpis, "business_units": business_units, "guidance": guidance, "commentary": commentary}


def parse_presentation(text: str) -> dict:
    return {"kpis": {}, "business_units": [], "guidance": {}, "commentary": []}


def parse(doc_type: str, text: str) -> dict:
    if doc_type == "press_release":
        return parse_press_release(text)
    if doc_type == "presentation":
        return parse_presentation(text)
    return {"kpis": {}, "business_units": [], "guidance": {}, "commentary": []}
